- hosts: test-deb
  tasks:
   - name: download py file
     get_url:
      src: 
      dest: /tmp/fetched

    - name: Installs pip
      apt: pkg=python-pip state=present update_cache=true
    - name: Installs module
      pip:
        name: tinyhtml

